version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timeServer_db
      MYSQL_USER: user
      MYSQL_PASSWORD: zaq1@WSX
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  moja-aplikacja:
    build: .
    container_name: moja-aplikacja
    restart: on-failure
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_DATABASE=timeServer_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=zaq1@WSX
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

volumes:
  mysql-data:
